cache:
  paths:
  - node_modules/

stages:
  - test

unit_test:
  image: node:latest
  stage: test
  variables:
    NODE_ENV: test
  script:
    - npm install --save-dev jest
    - npm install --global web-ext
    - npm test
    - npm web-ext --config=config.js lint
